### ISSUE TITLE
change license to (or add) MIT

### ISSUE THREAD

**Issue by nqzero** [jestan/kilim-maven-plugin#1]
i'm working on a new release of kilim (it's been semi stagnant for a few years and i've recently joined the team with sriram) and i've integrated your plugin and greatly improved the runtime weaving support so that it works reliably. your plugin uses the apache license, and the rest of kilim uses the MIT license. would you be willing to relicense using the MIT or give us permission to use it under the MIT ?

this isn't a major issue since the 2 licenses are compatible, but it would eliminate a little confusion

the current kilim 2.0 is https://github.com/nqzero/kilim

your stuff is in the "plugins" folder in the current version (but will be moving shortly into src/kilim/plugins and doc/plugins)

**Comment by jestan** [comment]
Done, Glad to see this tiny plugin is useful to you :)
